---
sidebar: sidebar
permalink: reference_supported_configs_94.html
keywords: ec2, instance, type, vm, explore, standard, premium, byol, capacity, maximum, virtual machine, Cloud Volumes ONTAP, supported, configurations
summary: Cloud Volumes ONTAP is available in several configurations in AWS and Azure.
---

= Supported configurations for Cloud Volumes ONTAP 9.4
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP is available in AWS and Azure in two pricing options: pay-as-you-go and Bring Your Own License (BYOL). For pay-as-you-go, you can choose from three configurations: Explore, Standard, or Premium.

== Cloud Volumes ONTAP for AWS

In AWS, you can deploy Cloud Volumes ONTAP as a single system or an HA pair.

[cols=5*,cols="h,d,d,d,d",options="header"]
|===
|
| Explore
| Standard
| Premium
| BYOL

| EC2 instance types  | m4.xlarge

a|
* m4.2xlarge
* r4.xlarge

a|
* c4.4xlarge
* c4.8xlarge
* m4.4xlarge
* r4.2xlarge

a|
* c4.4xlarge
* c4.8xlarge
* m4.xlarge
* m4.2xlarge
* m4.4xlarge
* r4.xlarge
* r4.2xlarge

| Underlying storage 4+| General Purpose SSDs, Provisioned IOPS SSDs, Throughput Optimized HDDs, and Cold HDDs, up to 16 TB per disk

| License capacity limit | 2 TB | 10 TB 2+| 368 TB

| Term 3+| Hourly | 6 or 12 months

|===

Notes:

. If you enable data tiering, a system’s capacity limit stays the same. The capacity limit includes both disks and object storage.

. Data tiering is supported with Cloud Volumes ONTAP Standard, Premium, and BYOL.

. When you choose an EC2 instance type, you can specify whether it is a shared instance or a dedicated instance.

. Enhanced write performance is supported when using EBS SSDs with Cloud Volumes ONTAP Standard, Premium, and BYOL.

. For AWS region support, see https://cloud.netapp.com/cloud-volumes-global-regions[Cloud Volumes Global Regions^].

== Cloud Volumes ONTAP for Azure

In Azure, you can deploy Cloud Volumes ONTAP as a single node system.

[cols=5*,cols="h,d,d,d,d",options="header"]
|===
|
| Explore
| Standard
| Premium
| BYOL

| Virtual machine types | DS3_v2

a|
* DS4_v2
* DS13_v2

a|
* DS5_v2
* DS14_v2

a|
* DS3_v2
* DS4_v2
* DS5_v2
* DS13_v2
* DS14_v2

| Underlying storage 4+| Standard HDD Managed Disks, Standard SSD Managed Disks, and Premium SSD Managed Disks, up to 32 TB per disk

| License capacity limit | 2 TB | 10 TB 2+| 368 TB

| Term 3+| Hourly | 12 months

|===

Notes:

. If you enable data tiering, a system’s capacity limit stays the same. The capacity limit includes both disks and object storage.

. Data tiering is not supported with the DS3_v2 virtual machine type.

. Enhanced write performance is enabled when using Azure Premium Storage disks, but not when using the DS3_v2 virtual machine type.

. For Azure region support, see https://cloud.netapp.com/cloud-volumes-global-regions[Cloud Volumes Global Regions^].
