---
sidebar: sidebar
permalink: reference_storage_limits_95.html
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM
summary: Cloud Volumes ONTAP has storage configuration limits to provide reliable operations. For best performance, do not configure your system at the maximum values.
---

= Storage limits for Cloud Volumes ONTAP 9.5
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP has storage configuration limits to provide reliable operations. For best performance, do not configure your system at the maximum values.

== System capacity limit

A system's capacity limit depends on the Cloud Volumes ONTAP license that you choose for the system.

[cols="40,60",width=65%,options="header"]
|===
| License
| Capacity limit

| Explore	| 2 TB
| Standard | 10 TB
| Premium | 368 TB
| BYOL | 368 TB

|===

Notes:

. For some configurations, disk limits prevent you from reaching the 368 TB capacity limit by using disks alone. In those cases, you can reach the 368 TB capacity limit by https://docs.netapp.com/us-en/occm/concept_data_tiering.html[tiering cold data to object storage^]. Refer to disk limits below for more details.

. If you enable data tiering, a system's capacity limit stays the same. The capacity limit includes both disks and object storage.

. In AWS, an HA pair's mirrored data does not count against the system capacity limit.
+
Data in an AWS HA pair is synchronously mirrored between the nodes so that the data is available in the event of failure. If you purchase an 8 TB disk on node A, Cloud Manager also allocates an 8 TB disk on node B that is used for mirrored data. While 16 TB of capacity was provisioned, only 8 TB counts against the license limit.

== Aggregate and disk limits in AWS

Cloud Volumes ONTAP uses AWS volumes as disks and groups them into _aggregates_. Aggregates provide storage to volumes.

=== Aggregate limits in AWS

[cols=2*,options="header,autowidth"]
|===
| Parameter
| Limit

| Maximum number of aggregates |
Single node: Same as the disk limit
HA pairs: 18 in a node ^1^
| Maximum aggregate size |	96 TB of raw capacity ^2^^,^ ^3^
| Disks per aggregate	| 1-6
| Maximum number of RAID groups per aggregate	| 1
|===

Notes:

. It is not possible to create 18 aggregates on both nodes in an HA pair because doing so would exceed the data disk limit.

. The maximum usable capacity of a 96 TB aggregate is 85.05 TB.

. The aggregate capacity limit is based on the disks that comprise the aggregate. The limit does not include object storage used for data tiering.

=== Data disk limits in AWS

The data disk limit is specific to disks that contain user data. The boot disk and root disk for each node are not included in this limit. Remember the following:

* Cloud Volumes ONTAP Explore and Standard support a lower capacity limit, so they cannot reach the maximum values.

* These numbers show just the _disk-based_ capacity. You can also tier cold data to S3 object storage until you reach the system capacity limit for your license.

==== Single node disk limit by EC2 instance type

The maximum disk size is 16 TB. The number of supported disks varies by instance type:

[cols=3*,options="header,autowidth"]
|===
| Instance type
| Max data disks per node
| Max disk-based capacity

| c4.4xlarge | 35 | 368 TB
| c4.8xlarge | 35 | 368 TB
| m4.xlarge | 35 | 368 TB
| m4.2xlarge | 35 | 368 TB
| m4.4xlarge | 35 | 368 TB
| m5.xlarge | 24 | 368 TB
| m5.2xlarge | 24 | 368 TB
| m5.4xlarge | 24 | 368 TB
| r4.xlarge | 35 | 368 TB
| r4.2xlarge | 35 | 368 TB
| r5.xlarge | 24 | 368 TB
| r5.2xlarge | 24 | 368 TB
|===

==== HA disk limit by EC2 instance type

The maximum disk size is 16 TB. The number of supported disks varies by instance type:

[cols=3*,options="header,autowidth"]
|===
| Instance type
| Max data disks per node
| Max disk-based capacity

| c4.4xlarge | 32 | 368 TB
| c4.8xlarge | 32 | 368 TB
| m4.xlarge | 32 | 368 TB
| m4.2xlarge | 32 | 368 TB
| m4.4xlarge | 32 | 368 TB
| m5.xlarge | 21 | 336 TB
| m5.2xlarge | 21 | 336 TB
| m5.4xlarge | 21 | 336 TB
| r4.xlarge | 32 | 368 TB
| r4.2xlarge | 32 | 368 TB
| r5.xlarge | 21 | 336 TB
| r5.2xlarge | 21 | 336 TB
|===

== Aggregate and disk limits in Azure

Cloud Volumes ONTAP uses Azure volumes as disks and groups them into _aggregates_. Aggregates provide storage to volumes.

=== Aggregate limits in Azure

[cols=2*,options="header,autowidth"]
|===
| Parameter
| Limit

| Maximum number of aggregates | Same as the disk limit
| Maximum aggregate size |
48 TB of raw capacity for single node ^1^^,^ ^2^
96 TB of raw capacity for HA pairs ^1^^,^ ^2^
| Number of disks per aggregate	| 1-12
| Maximum number of RAID groups per aggregate	| 1
|===

Notes:

. The maximum usable capacity of a 48 TB aggregate is 42.52 TB, while the maximum usable capacity of a 96 TB aggregate is 85.05 TB.

. The aggregate capacity limit is based on the disks that comprise the aggregate. The limit does not include object storage used for data tiering.

=== Data disk limits in Azure

The data disk limit is specific to disks that contain user data. The boot disk and root disk for each node are not included in this limit. Remember the following:

* Cloud Volumes ONTAP Explore and Standard support a lower capacity limit, so they cannot reach the maximum values.

* These numbers show just the _disk-based_ capacity. With single node systems, you can also tier cold data to Azure Blob object storage until you reach the system capacity limit for your license.

==== Single node disk limit by VM size

The maximum disk size for single node systems is 4 TB. The number of supported disks varies by VM size:

[cols=3*,options="header,autowidth"]
|===
| VM size
| Max data disks per node
| Max disk-based capacity

| DS3_v2 | 15 | 60 TB
| DS4_v2 | 31 | 124 TB
| DS5_v2 | 31 | 124 TB
| DS13_v2 | 63 | 252 TB
| DS14_v2 | 63 | 252 TB
|===

==== HA disk limit by VM size

The maximum disk size for HA pairs is 8 TB. The number of supported disks varies by VM size:

[cols=3*,options="header,autowidth"]
|===
| VM size
| Max data disks per node
| Max disk-based capacity

| DS4_v2 | 31 | 368 TB
| DS5_v2 | 31 | 368 TB
| DS13_v2 | 63 | 368 TB
| DS14_v2 | 63 | 368 TB
|===

== Logical storage limits

[cols=3*,options="header,autowidth"]
|===
| Logical storage
| Parameter
| Limit

| *Storage virtual machines (SVMs)*	| Maximum per node | One data-serving SVM and one or more SVMs used for disaster recovery ^1^
.2+| *Files*	| Maximum size | Volume size dependent
| Maximum per volume |	Volume size dependent, up to 2 billion
| *FlexClone volumes*	| Hierarchical clone depth ^2^ | 499
.3+| *FlexVol volumes*	| Maximum per node |	500
| Minimum size |	20 MB
| Maximum size |	76.55 TB of fully provisioned capacity ^3^
| *Qtrees* |	Maximum per FlexVol volume |	4,995
| *Snapshot copies* |	Maximum per FlexVol volume |	1,023

|===

Notes:

. Cloud Manager does not provide any setup or orchestration support for SVM disaster recovery. It also does not support storage-related tasks on any additional SVMs. You must use System Manager or the CLI for SVM disaster recovery.

. Hierarchical clone depth is the maximum depth of a nested hierarchy of FlexClone volumes that can be created from a single FlexVol volume.

. The specified limit is based on the assumption that you use Cloud Manager to create a volume and that you keep the aggregate free space ratio at 10 percent, which Cloud Manager sets by default.

== iSCSI storage limits

[cols=3*,options="header,autowidth"]
|===
| iSCSI storage
| Parameter
| Limit

.4+| *LUNs*	| Maximum per node |	1,024
| Maximum number of LUN maps |	1,024
| Maximum size	| 16 TB
| Maximum per volume	| 512
| *igroups*	| Maximum per node | 256
.2+| *Initiators*	| Maximum per node |	512
| Maximum per igroup	| 128
| *iSCSI sessions* |	Maximum per node | 1,024
.2+| *LIFs*	| Maximum per port |	32
| Maximum per portset	| 32
| *Portsets* |	Maximum per node |	256

|===
