---
sidebar: sidebar
permalink: reference_configs_aws_991.html
keywords: ec2, instance, type, explore, standard, premium, byol, capacity, maximum, virtual machine, Cloud Volumes ONTAP, supported, configurations, sizes, disks, networking, bandwidth, professional package
summary: A few licensing options are available for Cloud Volumes ONTAP. Each of these licensing options enables you to choose a configuration that meets your needs.
---

= Supported configurations for Cloud Volumes ONTAP 9.9.1 in AWS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Several licensing options are available for Cloud Volumes ONTAP. Each option enables you to choose a configuration that meets your needs.

== Licensing

You can pay for Cloud Volumes ONTAP in AWS using any of the following options.

[cols="22,40,16,22",width=100%,options="header"]
|===
| License
| Highlights
| Support
| Max system capacity

| PAYGO a|
* Pay-as-you-go by the hour through an AWS Marketplace subscription
* Available in three licensing options: Explore, Standard, and Premium | Included, but you must https://docs.netapp.com/us-en/occm/task_registering.html[activate support^]
a|
* Explore: 2 TB
* Standard: 10 TB
* Premium: 368 TB

a|
Capacity-based license:
Professional package a|
* Pay per TiB of capacity for one or more Cloud Volumes ONTAP systems
* Available through an annual contract from the AWS Marketplace or by bringing your own license (BYOL) purchased from NetApp
* Provides licensing for both Cloud Volumes ONTAP and Cloud Backup Service | Included | 2 PB

a|
Capacity-based license:
Essential package a|
* Pay per TiB of capacity for one or more Cloud Volumes ONTAP systems
* Available by bringing your own license (BYOL) purchased from NetApp
* Provides a la carte licensing for Cloud Volumes ONTAP (file storage, block storage, or disaster recovery) and your choice of add-on services | Included | 2 PB

a|
Capacity-based license:
Freemium package a|
* Use all Cloud Volumes ONTAP features free of charge from NetApp (cloud provider charges still apply)
* You can have up to 10 Freemium systems in your account | Not included | 500 GB

| Node-based license a|
* The previous generation BYOL for Cloud Volumes ONTAP
* Available for license renewals only | Included | 368 TB per license

|===

The following sections provide more details about each of these charging methods.

=== PAYGO

* Requires a subscription from the AWS Marketplace for pay-as-you-go pricing at an hourly rate.
* Offers Cloud Volumes ONTAP in three different licensing options: Explore, Standard, and Premium. Each license provides support for different amounts of storage and compute.
* A 30-day free trial is available for the first Cloud Volumes ONTAP system that you deploy in AWS.
** There are no hourly software charges, but AWS infrastructure charges still apply (compute, storage, and networking).
** When the free trial ends, you'll be charged hourly according to the selected license, as long as you subscribed. If you haven't subscribed, the system shuts down.
+
Cloud Manager prompts you to subscribe to the AWS Marketplace when you create a Cloud Volumes ONTAP system.
* Conversions to another licensing option isn't supported.
* Basic technical support is offered, but you must https://docs.netapp.com/us-en/occm/task_registering.html[register and activate the NetApp serial number associated with your system^].

https://aws.amazon.com/marketplace/pp/prodview-eap6ybxwk5ycg[View pricing information on the AWS Marketplace].

=== Capacity-based licensing

A capacity-based license enables you to pay for Cloud Volumes ONTAP per TiB of capacity. The license is associated with your NetApp account and enables you to create as many Cloud Volumes ONTAP systems as you need, as long as enough capacity is available through your license.

Capacity-based licensing is available in the form of a _package_. You can choose from the following packages.

Professional package::

* Provides licensing for both Cloud Volumes ONTAP and Cloud Backup Service at a lower price than purchasing them separately.
* The package is available as an annual contract from the AWS Marketplace or as a license (BYOL) purchased from NetApp.
* Support is included for the length of the subscription term.
* Conversions to another licensing option isn't supported.
* Each individual Cloud Volumes ONTAP system supports up to 2 PB of capacity through EBS disks and tiering to S3 object storage.

https://aws.amazon.com/marketplace/pp/prodview-q7dg6zwszplri[View pricing information on the AWS Marketplace^].

Essential package::

* Provides a la carte licensing for Cloud Volumes ONTAP:
** Cloud Volumes ONTAP single node or high availability with file storage, block storage, and/or secondary data (disaster recovery).
** Your choice of add-on NetApp Cloud Services like Cloud Backup, Cloud Data Sense, and more.
* Support is included for the length of the subscription term.
* Conversions to another licensing option isn't supported.
* Each individual Cloud Volumes ONTAP system supports up to 2 PB of capacity through EBS disks and tiering to S3 object storage.

Freemium package::

* Provides all Cloud Volumes ONTAP features free of charge from NetApp (cloud provider charges still apply).
* Support is not included.
* You can convert to another capacity-based package by adding the license to your account. Once the allocated capacity exceeds 500 GB, Cloud Manager automatically converts you to that charging method.
* You're limited to 500 GB of allocated capacity per Cloud Volumes ONTAP system.
* You can use up to 10 Cloud Volumes ONTAP systems with the Freemium charging method per NetApp account.

=== Node-based licensing

* The previous generation BYOL for Cloud Volumes ONTAP.
* A node-based license is available for license renewals only.
* Each Cloud Volumes ONTAP system supports up to 368 TB of capacity per license.
* Conversions to another licensing option isn't supported.
+
If you want to transition to capacity-based licensing, you can purchase a license, deploy a new Cloud Volumes ONTAP system, and then replicate the data to that new system.

== Supported number of nodes

Cloud Volumes ONTAP is available in AWS as a single node system and as a high-availability (HA) pair of nodes for fault tolerance and nondisruptive operations.

Upgrading a single node system to an HA pair is not supported. If you want to switch between a single node system and an HA pair, then you need to deploy a new system and replicate data from the existing system to the new system.

== Supported storage

Cloud Volumes ONTAP supports several types of EBS disks and S3 object storage for data tiering. The maximum storage capacity is determined by the license that you choose.

=== Storage support by license

Each license supports a different maximum system capacity. The maximum system capacity includes disk-based storage plus object storage used for data tiering. NetApp doesn’t support exceeding this limit.

[cols=6*,cols="h,d,d,d,d,d",options="header"]
|===
|
| PAYGO Explore
| PAYGO Standard
| PAYGO Premium
| BYOL
| Capacity-based licensing

| Maximum system capacity
(disks + object storage) ^1^ | 2 TB | 10 TB | 368 TB ^2^ | 368 TB per license ^2^ | 2 PB ^2,3^

| Supported disk types 5+a|
* General Purpose SSD (gp3 and gp2) ^4^
* Provisioned IOPS SSD (io1) ^4^
* Throughput Optimized HDD (st1) ^5^

| Cold data tiering to S3 | Not supported 4+| Supported

|===

. For an HA pair, the capacity limit is for the entire HA pair. It's not per node. For example, if you use the Premium license, you can have up to 368 TB of capacity between both nodes.

. For some configurations, disk limits prevent you from reaching the capacity limit by using disks alone. In those cases, you can reach the capacity limit by https://docs.netapp.com/us-en/occm/concept_data_tiering.html[tiering inactive data to object storage^]. For information about disk limits, refer to link:reference_limits_aws_991.html[storage limits].

. When using the Freemium package, Cloud Volumes ONTAP is limited to 500 GB.

. Enhanced write performance is enabled when using SSDs with Cloud Volumes ONTAP Standard, Premium, and BYOL.

. Tiering data to object storage is not recommended when using Throughput Optimized HDDs (st1).

=== Supported disk sizes

In AWS, an aggregate can contain up to 6 disks that are all the same type and size.

[cols=3*,options="header"]
|===

| General Purpose SSDs (gp3 and gp2)
| Provisioned IOPS SSDs (io1)
| Throughput Optimized HDDs (st1)

a|
* 100 GB
* 500 GB
* 1 TB
* 2 TB
* 4 TB
* 6 TB
* 8 TB
* 16 TB

a|
* 100 GB
* 500 GB
* 1 TB
* 2 TB
* 4 TB
* 6 TB
* 8 TB
* 16 TB

a|
* 500 GB
* 1 TB
* 2 TB
* 4 TB
* 6 TB
* 8 TB
* 16 TB

|===

== Supported EC2 compute

Each Cloud Volumes ONTAP license supports different EC2 instance types. For your convenience, the table below shows the vCPU, RAM, and bandwidth for each supported instance type. https://aws.amazon.com/ec2/instance-types/[You should refer to AWS for the latest and complete details about EC2 instance types^].

The bandwidths shown in the table below match the documented AWS limits for each instance type. These limits don't completely align with what Cloud Volumes ONTAP can provide. For the expected performance, refer to https://www.netapp.com/us/media/tr-4383.pdf[NetApp Technical Report 4383: Performance Characterization of Cloud Volumes ONTAP in Amazon Web Services with Application Workloads^].

[cols=8*,options="header"]
|===
| License
| Supported instance
| vCPU
| RAM
| Flash Cache ^1^
| Network bandwidth (Gbps)
| EBS bandwidth (Mbps)
| High write speed ^2^

| *Explore, BYOL, or capacity-based licensing*

| m5.xlarge | 4 | 16 | Not supported | Up to 10 | Up to 4,750 | Supported (single node only)

.3+| *Standard, BYOL, or capacity-based licensing*

| r5.xlarge | 4 | 32 | Not supported | Up to 10 | Up to 4,750 | Supported (single node only)

| m5a.2xlarge | 8 | 32 | Not supported | Up to 10 | Up to 2,880 | Supported

| m5.2xlarge | 8 | 32 | Not supported | Up to 10 | Up to 4,750 | Supported

.18+| *Premium, BYOL, or capacity-based licensing*

| m5n.2xlarge | 8 | 32 | Not supported | Up to 25 | Up to 4,750 | Supported

| r5.2xlarge | 8 | 64 | Not supported | Up to 10 | Up to 4,750 | Supported

| r5d.2xlarge | 8 | 64 | Supported | Up to 10 | Up to 4,750 | Supported

| c5d.4xlarge | 16 | 32 | Supported | Up to 10 | 4,570 | Supported

| m5.4xlarge | 16 | 64 | Not supported | Up to 10 | 4,750 | Supported

| m5d.8xlarge | 32 | 128 | Supported | 10 | 6,800 | Supported

| r5.8xlarge | 32 | 256 | Not supported | 10 | 6,800 | Supported

| c5.9xlarge | 36 | 72 | Not supported | 10 | 9,500 | Supported

| c5d.9xlarge | 36 | 72 | Supported | 10 | 9,500 | Supported

| c5n.9xlarge | 36 | 96 | Not supported | 50 | 9,500 | Supported

| c5a.12xlarge | 48 ^4^ | 96 | Not supported | 12 | 4,750 | Supported

| c5.18xlarge | 48 ^4^ | 144 | Not supported | 25 | 19,000 | Supported

| c5d.18xlarge | 48 ^4^ | 144 | Supported | 25 | 19,000 | Supported

| m5d.12xlarge | 48 | 192 | Supported | 12 | 9,500 | Supported

| c5n.18xlarge | 48 ^4^ | 192 | Not supported | 100 | 19,000 | Supported

| m5a.16xlarge | 48 ^4^ | 256 | Not supported | 12 | 9,500 | Supported

| m5.16xlarge | 48 ^4^ | 256 | Not supported | 20 | 13,600 | Supported

| r5.12xlarge ^3^ | 48 | 384 | Not supported | 10 | 9,500 | Supported

|===

. Some instance types include local NVMe storage, which Cloud Volumes ONTAP uses as _Flash Cache_. Flash Cache speeds access to data through real-time intelligent caching of recently read user data and NetApp metadata. It's effective for random read-intensive workloads, including databases, email, and file services. Compression must be disabled on all volumes to take advantage of the Flash Cache performance improvements. https://docs.netapp.com/us-en/occm/concept_flash_cache.html[Learn more about Flash Cache^].

. Cloud Volumes ONTAP supports high write speed with most instance types when using an HA pair. High write speed is supported with all instance types when using a single node system. https://docs.netapp.com/us-en/occm/concept_write_speed.html[Learn more about choosing a write speed^].

. The r5.12xlarge instance type has a known limitation with supportability. If a node unexpectedly reboots due to a panic, the system might not collect core files used to troubleshoot and root cause the problem. The customer accepts the risks and limited support terms and bears all support responsibility if this condition occurs. This limitation affects newly deployed HA pairs and HA pairs upgraded from 9.8. The limitation does not affect newly deployed single node systems.

. While these EC2 instance types support more than 48 vCPUs, Cloud Volumes ONTAP supports up to 48 vCPUs.

. When you choose an EC2 instance type, you can specify whether it is a shared instance or a dedicated instance.

. Cloud Volumes ONTAP can run on either a Reserved or On-demand EC2 instance. Solutions that use other instance types aren't supported.

== Supported regions

For AWS region support, see https://cloud.netapp.com/cloud-volumes-global-regions[Cloud Volumes Global Regions^].
