---
sidebar: sidebar
permalink: reference_configs_aws_97.html
keywords: ec2, instance, type, explore, standard, premium, byol, capacity, maximum, virtual machine, Cloud Volumes ONTAP, supported, configurations, sizes, disks
summary: Cloud Volumes ONTAP is available in AWS as a single node system or an HA pair. Two pricing options are available, pay as you go and Bring Your Own License (BYOL).
---

= Supported configurations for Cloud Volumes ONTAP 9.7 in AWS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP is available in AWS as a single node system or an HA pair. Two pricing options are available: pay as you go and Bring Your Own License (BYOL).

== Supported configurations by license

Cloud Volumes ONTAP is available in AWS as a single node system and as a high-availability (HA) pair of nodes for fault tolerance and nondisruptive operations.

Upgrading a single node system to an HA pair is not supported. If you want to switch between a single node system and an HA pair, then you need to deploy a new system and replicate data from the existing system to the new system.

[cols=5*,cols="h,d,d,d,d",options="header"]
|===
|
| PAYGO Explore
| PAYGO Standard
| PAYGO Premium
| BYOL
| Professional package

| Supported EC2 instance types ^1^
a|
* m4.xlarge
* m5.xlarge

a|
* m4.2xlarge
* m5.2xlarge
* r4.xlarge
* r5.xlarge

a|
* c4.4xlarge
* c4.8xlarge
* c5.9xlarge
* c5.18xlarge
* c5d.4xlarge ^2^
* c5d.9xlarge ^2^
* c5d.18xlarge ^2^
* c5n.9xlarge ^3^
* c5n.18xlarge ^3^
* m4.4xlarge
* m5.4xlarge
* m5.16xlarge
* m5d.8xlarge ^2^
* m5d.12xlarge ^2^
* r4.2xlarge
* r5.2xlarge
* r5.8xlarge
* r5.12xlarge ^4^
* r5d.2xlarge ^2^

.2+a|
* c4.4xlarge
* c4.8xlarge
* c5.9xlarge
* c5.18xlarge
* c5d.4xlarge ^2^
* c5d.9xlarge ^2^
* c5d.18xlarge ^2^
* c5n.9xlarge ^3^
* c5n.18xlarge ^3^
* m4.xlarge
* m4.2xlarge
* m4.4xlarge
* m5.xlarge
* m5.2xlarge
* m5.4xlarge
* m5.16xlarge
* m5d.8xlarge ^2^
* m5d.12xlarge ^2^
* r4.xlarge
* r4.2xlarge
* r5.xlarge
* r5.2xlarge
* r5.8xlarge
* r5.12xlarge ^4^
* r5d.2xlarge ^2^

| Supported disk types ^5^ 5+| General Purpose SSDs (gp3 and gp2), Provisioned IOPS SSDs (io1), and Throughput Optimized HDDs (st1) ^6^

| Cold data tiering to S3 | Not supported 4+| Supported

| Maximum system capacity
(disks + object storage) | 2 TB | 10 TB | 368 TB ^7^ | 368 TB per license ^7^ | 2 PB ^7^

|===

Notes:

. When you choose an EC2 instance type, you can specify whether it is a shared instance or a dedicated instance.

. These instance types include local NVMe storage, which Cloud Volumes ONTAP uses as _Flash Cache_. Flash Cache speeds access to data through real-time intelligent caching of recently read user data and NetApp metadata. It is effective for random read-intensive workloads, including databases, email, and file services. Compression must be disabled on all volumes to take advantage of the Flash Cache performance improvements. https://docs.netapp.com/us-en/occm/concept_flash_cache.html[Learn more^].

. c5n.9xlarge and c5n.18xlarge are supported starting with 9.7 P5.

. The r5.12xlarge instance type has a known limitation with supportability. If a node unexpectedly reboots due to a panic, the system might not collect core files used to troubleshoot and root cause the problem. The customer accepts the risks and limited support terms and bears all support responsibility if this condition occurs.

. Enhanced write performance is enabled when using SSDs with Cloud Volumes ONTAP Standard, Premium, and BYOL.

. Tiering data to object storage is not recommended when using Throughput Optimized HDDs (st1).

. For some HA configurations, disk limits prevent you from reaching the capacity limit by using disks alone. In those cases, you can reach the capacity limit by https://docs.netapp.com/us-en/occm/concept_data_tiering.html[tiering inactive data to object storage^]. For information about disk limits, refer to link:reference_limits_aws_97.html[storage limits].

. For AWS region support, see https://cloud.netapp.com/cloud-volumes-global-regions[Cloud Volumes Global Regions^].

. Cloud Volumes ONTAP can run on either a Reserved or On-demand VM instance from your cloud provider. Solutions that use other VM instance types aren't supported.

== Supported disk sizes

In AWS, an aggregate can contain up to 6 disks that are all the same type and size.

[cols=3*,options="header"]
|===

| General Purpose SSD (gp3 and gp2)
| Provisioned IOPS SSD (io1)
| Throughput Optimized HDD (st1)

a|
* 100 GB
* 500 GB
* 1 TB
* 2 TB
* 4 TB
* 6 TB
* 8 TB
* 16 TB

a|
* 100 GB
* 500 GB
* 1 TB
* 2 TB
* 4 TB
* 6 TB
* 8 TB
* 16 TB

a|
* 500 GB
* 1 TB
* 2 TB
* 4 TB
* 6 TB
* 8 TB
* 16 TB

|===
