---
sidebar: sidebar
permalink: reference_configs_gcp_990.html
keywords: google, gcp, google cloud platform, explore, standard, premium, byol, paygo, disks, supported, capacity, machine types, sizes, HA, high availability, HA pairs
summary: Several Cloud Volumes ONTAP configurations are supported in GCP.
---

= Supported configurations for Cloud Volumes ONTAP 9.9.0 in GCP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Several Cloud Volumes ONTAP configurations are supported in GCP.

== Supported configurations by license

Cloud Volumes ONTAP is available in Google Cloud Platform as a single node system and as a high-availability (HA) pair of nodes for fault tolerance and nondisruptive operations.

Upgrading a single node system to an HA pair is not supported. If you want to switch between a single node system and an HA pair, then you need to deploy a new system and replicate data from the existing system to the new system.

=== Single node systems

You can choose from the following configurations when deploying Cloud Volumes ONTAP as a single-node system in GCP.

[cols=7*,cols="h,d,d,d,d,d,d",options="header"]
|===
|
| PAYGO Explore
| PAYGO Standard
| PAYGO Premium
| Node-based license
| Capacity-based license
| Freemium

| Supported machine types ^1^
a|
* n2-standard-4
a|
* n1-standard-8
* n2-standard-8
a|
* n1-standard-32
* n2-standard-32
3+a|
* n1-standard-8
* n1-standard-32
* n2-standard-4
* n2-standard-8
* n2-standard-32

| Supported disk types ^2^ 6+| Zonal persistent disks (SSD and standard)

| Cold data tiering to object storage | Not supported 5+| Supported

| Maximum system capacity
(disks + object storage) ^3^ | 2 TB | 10 TB | 368 TB | 368 TB per license | 2 PB | 500 GB

|===

Notes:

. The custom-4-16384 machine type is no longer supported with new Cloud Volumes ONTAP systems.
+
If you have an existing system running on this machine type, you can keep using it, but we recommend switching to the n2-standard-4 machine type.

. Enhanced write performance is enabled when using SSDs.

. Disk limits might prevent you from reaching the maximum system capacity limit by using disks alone. You can reach the capacity limit by https://docs.netapp.com/us-en/occm/concept_data_tiering.html[tiering inactive data to object storage^].
+
link:reference_limits_gcp_990.html[Learn more about disk limits in GCP].

. The Cloud Manager interface shows an additional supported machine type for Standard and BYOL: n1-highmem-4. However, this machine type isn't meant for production environments. We've made it available for a specific lab environment only.

. For Google Cloud Platform region support, see https://cloud.netapp.com/cloud-volumes-global-regions[Cloud Volumes Global Regions^].

. Cloud Volumes ONTAP can run on either a Reserved or On-demand VM instance from your cloud provider. Solutions that use other VM instance types aren't supported.

=== HA pairs

You can choose from the following configurations when deploying Cloud Volumes ONTAP as an HA pair in GCP.

[cols=7*,cols="h,d,d,d,d,d,d",options="header"]
|===
|
| PAYGO Explore
| PAYGO Standard
| PAYGO Premium
| Node-based license
| Capacity-based license
| Freemium

| Supported machine types ^1^
a|
* n2-standard-4
a|
* n1-standard-8
* n2-standard-8
a|
* n1-standard-32
* n2-standard-32
3+a|
* n1-standard-8
* n1-standard-32
* n2-standard-4
* n2-standard-8
* n2-standard-32

| Supported disk types ^2^ 6+| Zonal persistent disks (SSD and standard)

| Cold data tiering to object storage | Not supported 5+| Supported

| Maximum system capacity
(disks + object storage) ^3^ | 2 TB | 10 TB | 368 TB | 368 TB per license | 2 PB | 500 GB

|===

Notes:

. The custom-4-16384 machine type is no longer supported with new Cloud Volumes ONTAP systems.
+
If you have an existing system running on this machine type, you can keep using it, but we recommend switching to the n2-standard-4 machine type.

. Enhanced write performance is enabled when using SSDs.

. Disk limits might prevent you from reaching the maximum system capacity limit by using disks alone. You can reach the capacity limit by https://docs.netapp.com/us-en/occm/concept_data_tiering.html[tiering inactive data to object storage^].
+
link:reference_limits_gcp_990.html[Learn more about disk limits in GCP].

. The Cloud Manager interface shows an additional supported machine type for Standard and BYOL: n1-highmem-4. However, this machine type isn't meant for production environments. We've made it available for a specific lab environment only.

. For Google Cloud Platform region support, see https://cloud.netapp.com/cloud-volumes-global-regions[Cloud Volumes Global Regions^].

. Cloud Volumes ONTAP can run on either a Reserved or On-demand VM instance from your cloud provider. Solutions that use other VM instance types aren't supported.

== Supported disk sizes

In GCP, an aggregate can contain up to 6 disks that are all the same type and size. The following disk sizes are supported:

* 100 GB
* 500 GB
* 1 TB
* 2 TB
* 4 TB
* 8 TB
* 16 TB
* 64 TB
