---
sidebar: sidebar
permalink: reference_supported_configs_95.html
keywords: ec2, instance, type, vm, explore, standard, premium, byol, capacity, maximum, virtual machine, Cloud Volumes ONTAP, supported, configurations
summary: Cloud Volumes ONTAP is available in several configurations in AWS and Azure.
---

= Supported configurations for Cloud Volumes ONTAP 9.5
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP is available in two pricing options: pay-as-you-go and Bring Your Own License (BYOL). For pay-as-you-go, you can choose from three configurations: Explore, Standard, or Premium.

ifdef::95-aws[]
== Cloud Volumes ONTAP for AWS

In AWS, you can deploy Cloud Volumes ONTAP as a single system or as an HA pair.

[cols=5*,cols="h,d,d,d,d",options="header"]
|===
|
| Explore
| Standard
| Premium
| BYOL

| EC2 instance types  | m4.xlarge

a|
* m4.2xlarge
* r4.xlarge

a|
* c4.4xlarge
* c4.8xlarge
* m4.4xlarge
* r4.2xlarge

a|
* c4.4xlarge
* c4.8xlarge
* m4.xlarge
* m4.2xlarge
* m4.4xlarge
* r4.xlarge
* r4.2xlarge

| Capacity limit | 2 TB | 10 TB
2+<a|
368 TB (360 TB for HA)

| Term 3+| Hourly | 6 or 12 months

|===

Notes:

. When you choose an EC2 instance type, you can specify whether it is a shared instance or a dedicated instance.

. Enhanced write performance is supported when using EBS SSDs with Cloud Volumes ONTAP Standard, Premium, and BYOL.

. Data tiering is supported with Cloud Volumes ONTAP Standard, Premium, and BYOL.

. If you enable data tiering, a system's capacity limit stays the same. The limit is spread across the performance tier and the capacity tier.

. For AWS region support, see https://docs.netapp.com/us-en/occm/reference_regions.html#supported-aws-regions[Supported AWS regions].
endif::[]
== Cloud Volumes ONTAP for Azure

In Azure, you can deploy Cloud Volumes ONTAP as a single node system or as an HA pair.

=== Single node systems

You can choose from the following configurations when deploying Cloud Volumes ONTAP as a single-node system in Azure:

[cols=5*,cols="h,d,d,d,d",options="header"]
|===
|
| Explore
| Standard
| Premium
| BYOL

| Virtual machine types | DS3_v2

a|
* DS4_v2
* DS13_v2

a|
* DS5_v2
* DS14_v2

a|
* DS3_v2
* DS4_v2
* DS5_v2
* DS13_v2
* DS14_v2

| Underlying storage 4+| Standard HDD Managed Disks or Premium SSD Managed Disks, up to 4 TB per disk

| Capacity limit | 2 TB | 10 TB 2+| 252 TB

| Term 3+| Hourly | 12 months

|===

Notes:

. The capacity limit is less for the following VM types because of virtual machine disk limits:
* DS3: 60 TB
* DS4 and DS13: 124 TB

. If you enable data tiering, a system's capacity limit stays the same. The limit is spread across the performance tier and the capacity tier.

. Data tiering is not supported with the DS3_v2 virtual machine type.

. Enhanced write performance is supported when using Azure Premium Storage disks, but not when using the DS3_v2 virtual machine type.

. For Azure region support, see https://docs.netapp.com/us-en/occm/reference_regions.html#supported-azure-regions[Supported Azure regions].

=== HA pairs

You can choose from the following configurations when deploying Cloud Volumes ONTAP as an HA pair in Azure:

[cols=5*,cols="h,d,d,d,d",options="header"]
|===
|
| Explore
| Standard
| Premium
| BYOL

| Virtual machine types | Not supported

a|
* DS4_v2
* DS13_v2

a|
* DS5_v2
* DS14_v2

a|
* DS4_v2
* DS5_v2
* DS13_v2
* DS14_v2

| Underlying storage | Not supported 3+| Premium page blobs, up to 8 TB per disk

| Capacity limit | Not supported | 10 TB 2+| 368 TB

| Term | Not supported 2+| Hourly | 12 months

|===

Notes:

. The capacity limit for DS4 and DS13 systems is less (248 TB) because of virtual machine disk limits.

. Data tiering is not supported with HA pairs.

. For Azure region support, see https://docs.netapp.com/us-en/occm/reference_regions.html#supported-azure-regions[Supported Azure regions].
