---
sidebar: sidebar
permalink: reference_new_990.html
keywords: what's new, new, features, release notes, enhancements
summary: Cloud Volumes ONTAP 9.9.0 includes several new features and enhancements.
---

= What's new in Cloud Volumes ONTAP 9.9.0
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP 9.9.0 includes several new features and enhancements.

Additional features and enhancements are also introduced in the latest versions of Cloud Manager. See the https://docs.netapp.com/us-en/occm/reference_new_occm.html[Cloud Manager Release Notes^] for details.

== Latest update (21 Apr 2021)

In AWS, you can now configure up to 24 storage VMs (SVMs) for disaster recovery (DR). The previous limit was 12 storage VMs used for DR.

link:reference_limits_aws_990.html#storage-vm-limits[Learn more about storage VM limits].

== Latest updates (12 Apr 2021)

A few updates have been made since Cloud Volumes ONTAP 9.9.0 was released.

*AWS updates*

* Cloud Volumes ONTAP now supports General Purpose SSD (gp3) disks, starting with the 9.7 release. gp3 disks are the lowest-cost SSDs that balance cost and performance for a broad range of workloads.
+
https://docs.netapp.com/us-en/occm/task_planning_your_config.html#sizing-your-system-in-aws[Learn more about using gp3 disks with Cloud Volumes ONTAP^].

* Cloud Volumes ONTAP no longer supports Cold HDD (sc1) disks.

These EBS disk changes were introduced as part of Cloud Manager 3.9.5.

*Azure updates*

* New E series VM types are supported:

** E4s_v3 with single node systems using PAYGO Explore or BYOL
** E8s_v3 with single node systems using PAYGO Standard or BYOL, and HA pairs using PAYGO Premium or BYOL
** E64is_v3 with single node systems using PAYGO Premium or BYOL

* Up to 24 storage VMs (SVMs) are supported with Cloud Volumes ONTAP BYOL. Those 24 storage VMs can serve data or be configured for disaster recovery (DR).
+
The previous limit in Azure was 12 storage VMs used for DR.

== Improved write performance

This release includes improved write performance for Cloud Volumes ONTAP in all cloud providers and on all configurations.

== Support for new EC2 instance types

Cloud Volumes ONTAP is now supported with the following Amazon EC2 instance types:

* m5a.2xlarge with Standard and BYOL
* m5a.16xlarge with Premium and BYOL
* c5a.12xlarge with Premium and BYOL

Learn more about https://aws.amazon.com/ec2/instance-types/m5/[M5a instances^] and https://aws.amazon.com/ec2/instance-types/c5/[C5a instances^].

link:reference_configs_aws_990.html[View supported configurations in AWS].

== Support for 24 storage VMs in Azure

24 storage VMs are now supported with Cloud Volumes ONTAP in Azure when you bring your own license (BYOL).

An add-on license is required for each additional _data-serving_ storage VM beyond the first storage VM that comes with Cloud Volumes ONTAP by default. Contact your account team to obtain an SVM add-on license.

Storage VMs that you configure for disaster recovery (DR) don't require an add-on license (they are free of charge), but they do count against the storage VM limit.

link:reference_limits_azure_990.html#storage-vm-limits[Learn more about storage VM limits in Azure].

https://docs.netapp.com/us-en/occm/task_managing_svms_azure.html[Learn how to create data-serving storage VMs for Cloud Volumes ONTAP in Azure^].

== Required version of the Cloud Manager Connector

The Cloud Manager Connector must be running version 3.9.4 or later to deploy new Cloud Volumes ONTAP 9.9.0 systems and to upgrade existing systems to 9.9.0.

== Changes introduced with Cloud Manager 3.9.4

The Cloud Manager 3.9.4 release includes a few enhancements for the management of Cloud Volumes ONTAP, including enhancements to AWS KMS support, shared VPC support in Google Cloud, and reduced IPs in Google Cloud.

Go to the https://docs.netapp.com/us-en/occm/reference_new_occm.html[Cloud Manager Release Notes^] for more details about the 3.9.4 release.

== Upgrade notes

* Upgrades of Cloud Volumes ONTAP must be completed from Cloud Manager. You should not upgrade Cloud Volumes ONTAP by using System Manager or the CLI. Doing so can impact system stability.

* You can upgrade to Cloud Volumes ONTAP 9.9.0 from the 9.8 release. Cloud Manager will prompt you to upgrade your existing Cloud Volumes ONTAP 9.8 systems to the 9.9.0 release.
+
http://docs.netapp.com/us-en/occm/task_updating_ontap_cloud.html#upgrading-cloud-volumes-ontap-from-cloud-manager-notifications[Learn how to upgrade when Cloud Manager notifies you^].

* The upgrade of a single node system takes the system offline for up to 25 minutes, during which I/O is interrupted.

* Upgrading an HA pair is nondisruptive and I/O is uninterrupted. During this nondisruptive upgrade process, each node is upgraded in tandem to continue serving I/O to clients.

=== c4, m4, and r4 instance types

Starting with the 9.8 release, c4, m4, and r4 instance types aren't supported with new Cloud Volumes ONTAP systems. If you have an existing Cloud Volumes ONTAP system that's running on a c4, m4, or r4 instance type, you can still upgrade to this release.

We recommend changing to an instance type in the c5, m5, or r5 instance family.
