---
sidebar: sidebar
permalink: reference_new_95.html
keywords: what's new, new, features, release notes, enhancements
summary: Cloud Volumes ONTAP 9.5 includes several new features and enhancements.
---

= What's new in Cloud Volumes ONTAP 9.5
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP 9.5 includes several new features and enhancements.

NOTE: Additional features and enhancements are also introduced in the latest versions of Cloud Manager. See the https://docs.netapp.com/us-en/occm/reference_new_occm.html[Cloud Manager Release Notes] for details.

== 9.5 P1 patch (18 Mar 2019)

The 9.5 P1 patch release for Cloud Volumes ONTAP is now available for all configurations. Cloud Manager will prompt you to upgrade your existing systems to this patch release.

If you have an existing HA pair in Azure, NetApp will contact you to help you apply the P1 patch release.

https://mysupport.netapp.com/products/cloud_ontap/9.5P1/index.html[Click here to see the bugs fixed in the P1 patch^].

== Cloud Volumes ONTAP HA is now GA in Azure (18 Mar 2019)

With the release of the 9.5 P1 patch, HA pairs in Azure are now Generally Available (GA). A Preview license is no longer required.

The GA release is available in 19 Azure regions with the exception of the following regions:

* Central US
* North Central US
* US Gov regions
* West US
* West Central US

Maintenance in these regions can prevent the creation of Cloud Volumes ONTAP and prevent failover from taking place. We plan to support these regions as soon as the maintenance is completed.

https://cloud.netapp.com/cloud-volumes-global-regions[See a full list of supported Azure regions^].

== 9.5 GA for AWS and Azure (4 Feb 2019)

The General Availability (GA) release of Cloud Volumes ONTAP 9.5 is now available in AWS and in Microsoft Azure (for single node systems only in Azure). The GA release includes stability fixes, new and deprecated features in AWS, and a change to system capacity limits.

=== 368 TB capacity limit for all Premium and BYOL configurations

The system capacity limit for Cloud Volumes ONTAP Premium and BYOL is now 368 TB across all configurations: single node and HA in both AWS and Azure.

For some configurations, disk limits prevent you from reaching the 368 TB capacity limit by using disks alone. In those cases, you can reach the 368 TB capacity limit by https://docs.netapp.com/us-en/occm/concept_data_tiering.html[tiering inactive data to object storage^]. For example, a single node system in Azure could have 252 TB of disk-based capacity, which would allow up to 116 TB of inactive data in Azure Blob storage.

For information about disk limits, refer to link:reference_storage_limits_95.html[storage limits].

=== Support for M5 and R5 instances in AWS

Cloud Volumes ONTAP now supports several instance types in the M5 and R5 families:

[cols=4*,options="header"]
|===
| Explore
| Standard
| Premium
| BYOL

| m5.xlarge
a|
* m5.2xlarge
* r5.xlarge
a|
* m5.4xlarge
* r5.2xlarge
a|
* m5.xlarge
* m5.2xlarge
* m5.4xlarge
* r5.xlarge
* r5.2xlarge

|===

These instances use a hypervisor that is based on KVM technology. As a result, the instances support a smaller number of data disks than other instance types: up to 24 data disks for single-node systems and 21 data disks for HA pairs. link:reference_storage_limits_95.html[Learn about storage limits].

Learn more about https://aws.amazon.com/ec2/instance-types/m5/[M5 instances^] and https://aws.amazon.com/ec2/instance-types/r5/[R5 instances^].

=== Support for NetApp Volume Encryption in AWS

https://www.netapp.com/us/media/ds-3899.pdf[NetApp Volume Encryption (NVE)^] is a software-based technology for encrypting data at rest one volume at a time. Data, Snapshot copies, and metadata are encrypted. Access to the data is given by a unique XTS-AES-256 key, one per volume.

At this time, Cloud Volumes ONTAP supports NetApp Volume Encryption with an external key management server. An Onboard Key Manager is not supported. You can find the supported key managers in the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^] under the *Key Managers* solution.

You need to set up NetApp Volume Encryption from the CLI. You can then use either the CLI or System Manager to enable encryption on specific volumes. Cloud Manager does not support NetApp Volume Encryption at this time.

https://docs.netapp.com/us-en/occm/task_encrypting_volumes.html[Learn how to set up NetApp Volume Encryption^]

NOTE: NetApp Volume Encryption is a different encryption technology than Cloud Volumes ONTAP encryption, which encrypted data at the aggregate level and is now deprecated. An upgrade between these two encryption technologies is not possible. See <<Deprecated features in AWS>> for more information.

=== Deprecated features in AWS

Two features are no longer supported in the 9.5 release.

==== Cloud Volumes ONTAP encryption is no longer supported in AWS

Data-at-rest encryption of aggregates using external key managers is no longer supported. If you are currently using this feature and you want to upgrade, you must launch a new 9.5 system and then https://docs.netapp.com/us-en/occm/task_replicating_data.html[replicate data] to that system.

You can encrypt data by using NetApp Volume Encryption or by using the AWS Key Management Service (KMS).

==== c4.2xlarge is no longer supported

The c4.2xlarge instance type is not supported with the 9.5 release. If you are currently using this instance type, you must first https://docs.netapp.com/us-en/occm/task_modifying_ontap_cloud.html#changing-the-instance-or-virtual-machine-type-for-cloud-volumes-ontap[change to a new instance type] before you upgrade to the 9.5 release.

== 9.5 RC1 for Azure (4 Dec 2018)

Cloud Volumes ONTAP 9.5 RC1 is now available in Microsoft Azure. The 9.5 release will be available in AWS at a later date.

=== Preview of high-availability (HA) pairs in Microsoft Azure

A preview of Cloud Volumes ONTAP HA pairs in Microsoft Azure is now available. An HA pair provides enterprise reliability and continuous operations in case of failures in your cloud environment. Similar to a physical ONTAP cluster, storage in an Azure HA pair is shared between the two nodes.

HA pairs in Azure are available as a preview. You can request a preview license by contacting us at ng-Cloud-Volume-ONTAP-preview@netapp.com.

https://docs.netapp.com/us-en/occm/concept_ha_azure.html[Learn more about HA pairs in Azure^].

=== Improved networking performance in Azure

Cloud Volumes ONTAP systems are now enabled with https://docs.microsoft.com/en-us/azure/virtual-network/create-vm-accelerated-networking-cli[Accelerated Networking^] in Azure. Cloud Manager enables Accelerated Networking when you upgrade to 9.5 and when you deploy new 9.5 systems.

=== Support for new Azure regions

You can now deploy Cloud Volumes ONTAP in the France Central region.

//You can now deploy Cloud Volumes ONTAP in the following Azure regions:

//* Australia Central
//* Australia Central 2
//* France Central
//* France South

=== Support for NetApp Volume Encryption in Azure

https://www.netapp.com/us/media/ds-3899.pdf[NetApp Volume Encryption (NVE)^] is a software-based technology for encrypting data at rest one volume at a time. Data, Snapshot copies, and metadata are encrypted. Access to the data is given by a unique XTS-AES-256 key, one per volume.

At this time, Cloud Volumes ONTAP supports NetApp Volume Encryption with an external key management server. An Onboard Key Manager is not supported. You can find the supported key managers in the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^] under the *Key Managers* solution.

You need to set up NetApp Volume Encryption from the CLI. You can then use either the CLI or System Manager to enable encryption on specific volumes. Cloud Manager does not support NetApp Volume Encryption at this time.

https://docs.netapp.com/us-en/occm/task_encrypting_volumes.html[Learn how to set up NetApp Volume Encryption^]

== Upgrade notes

* You can upgrade to Cloud Volumes ONTAP 9.5 from the 9.4 or 9.3 release. You can perform the upgrade directly from Cloud Manager.
+
To understand version requirements, refer to http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-dot-upgrade/GUID-AC0EB781-583F-4C90-A4C4-BC7B14CEFD39.html[ONTAP 9 Documentation: Cluster update requirements^].

* When you use Cloud Manager to upgrade a single-node system, the upgrade process takes the system offline for up to 25 minutes, during which I/O is interrupted.

* Upgrades of HA pairs are nondisruptive. A nondisruptive upgrade upgrades both nodes in an HA pair concurrently while maintaining service to clients.
