---
sidebar: sidebar
permalink: reference_new_98.html
keywords: what's new, new, features, release notes, enhancements
summary: Cloud Volumes ONTAP 9.8 includes several new features and enhancements.
---

= What's new in Cloud Volumes ONTAP 9.8
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP 9.8 includes several new features and enhancements.

Additional features and enhancements are also introduced in the latest versions of Cloud Manager. See the https://docs.netapp.com/us-en/occm/reference_new_occm.html[Cloud Manager Release Notes^] for details.

== 9.8 RC1 (8 Nov 2020)

Cloud Volumes ONTAP 9.8 RC1 is now available in AWS, Azure, and Google Cloud Platform. In addition to the features introduced with https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508[ONTAP 9.8^], this release of Cloud Volumes ONTAP includes the following:

* <<High-availability pairs in Google Cloud>>
* <<Support for 24 SVMs in AWS>>
* <<High write speed with HA pairs in AWS and Azure>>
* <<Fixes for Azure NIC detach events and maintenance events>>
* <<Core disk for single node systems in AWS>>

=== High-availability pairs in Google Cloud

Cloud Volumes ONTAP high-availability (HA) pairs are now available in Google Cloud.

An HA pair provides enterprise reliability and continuous operations in case of failures in your cloud environment. Similar to Cloud Volumes ONTAP in AWS, an HA pair in Google Cloud includes two Cloud Volumes ONTAP nodes whose data is synchronously mirrored between each other, and a mediator instance that provides a communication channel to assist in storage takeover and giveback.

View link:reference_configs_gcp_98.html[supported configurations] and link:reference_limits_gcp_98.html[storage limits].

//Learn how to deploy an HA pair in Google Cloud.

=== Support for 24 storage VMs in AWS

Up to 24 storage VMs are now supported with Cloud Volumes ONTAP in AWS when you use a C5, M5, or R5 instance type and bring your own license (BYOL). link:reference_limits_aws_98.html[Learn more about storage VM limits].

=== High write speed with HA pairs in AWS and Azure

Cloud Volumes ONTAP now supports high write speed with HA pairs in AWS and Azure when using a specific instance or VM type. High write speed is a good choice if fast write performance is required for your workload and you can withstand the risk of data loss in the event of an unplanned system outage.

Before you choose a write speed, you should understand the differences between the normal and high settings and the risks and recommendations when using high write speed.

https://docs.netapp.com/us-en/occm/concept_write_speed.html[Learn more^].

=== Fixes for Azure NIC detach events and maintenance events

This release provides several improvements for how Cloud Volumes ONTAP handles Azure freeze events, Azure NIC detach events, and other Azure maintenance activities (for example, Virtual Function Revoke). Cloud Volumes ONTAP is more fault tolerant in this release and will handle Azure events more gracefully, with a reduced likelihood of service disruption or cluster degradation.

=== Core disk for single node systems in AWS

Cloud Manager now allocates a core disk to new Cloud Volumes ONTAP 9.8 single node systems when you use a C5, M5, or R5 instance type. The core disk expands the ability to switch between supported instance types, enhances the system's ability to collect core files when issues occur, and provides the ability to support larger instance types in the future.

The core disk is a General Purpose SSD with 540 GB.

NOTE: With the addition of this core disk, one less data disk is now supported on single node systems that use these instance types. link:reference_limits_aws_98.html[Learn more about storage limits in AWS].

== Upgrade notes

* Upgrades of Cloud Volumes ONTAP must be completed from Cloud Manager. You should not upgrade Cloud Volumes ONTAP by using System Manager or the CLI. Doing so can impact system stability.

* You can upgrade to Cloud Volumes ONTAP 9.8 from the 9.7 release. Cloud Manager will prompt you to upgrade your existing Cloud Volumes ONTAP 9.7 systems to the 9.8 release.
+
http://docs.netapp.com/us-en/occm/task_updating_ontap_cloud.html#upgrading-cloud-volumes-ontap-from-cloud-manager-notifications[Learn how to upgrade when Cloud Manager notifies you^].

* The upgrade of a single node system takes the system offline for up to 25 minutes, during which I/O is interrupted.

* Upgrading an HA pair is nondisruptive and I/O is uninterrupted. During this nondisruptive upgrade process, each node is upgraded in tandem to continue serving I/O to clients.
