---
sidebar: sidebar
permalink: reference_new_96.html
keywords: what's new, new, features, release notes, enhancements
summary: Cloud Volumes ONTAP 9.6 includes several new features and enhancements.
---

= What's new in Cloud Volumes ONTAP 9.6
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP 9.6 includes several new features and enhancements.

Additional features and enhancements are also introduced in the latest versions of Cloud Manager. See the https://docs.netapp.com/us-en/occm/reference_new_occm.html[Cloud Manager Release Notes^] for details.

== 9.6 P8 (2 June 2020)

The 9.6 P8 patch release for Cloud Volumes ONTAP is now available through Cloud Manager 3.8 and later. Cloud Manager will prompt you to upgrade your existing systems to this patch release. https://mysupport.netapp.com/products/cloud_ontap/9.6P8/index.html[View the list of bugs fixed in the P8 patch^].

== 9.6 P7 (8 Apr 2020)

The 9.6 P7 patch release for Cloud Volumes ONTAP is now available through Cloud Manager 3.8 and later. Cloud Manager will prompt you to upgrade your existing systems to this patch release. https://mysupport.netapp.com/products/cloud_ontap/9.6P7/index.html[View the list of bugs fixed in the P7 patch^].

== 9.6 P6 (6 Mar 2020)

The 9.6 P6 patch release for Cloud Volumes ONTAP is now available through Cloud Manager 3.8 and later. Cloud Manager will prompt you to upgrade your existing systems to this patch release. https://mysupport.netapp.com/products/cloud_ontap/9.6P6/index.html[View the list of bugs fixed in the P6 patch^].

== AWS updates (16 Feb 2020)

We've introduced support for new EC2 instances and a change in the number of supported data disks.

=== Support for new instances

A few new EC2 instance types are now supported with Cloud Volumes ONTAP 9.6 when using a Premium or BYOL license:

* c5.9xlarge
* c5d.18xlarge ^1,2^
* m5d.8xlarge ^1,2^

^1^ These instance types include local NVMe storage, which Cloud Volumes ONTAP uses as _Flash Cache_. https://docs.netapp.com/us-en/occm/task_enabling_flash_cache.html[Learn more^].

^2^ These instance types are supported with 9.6 P3 and later.

https://aws.amazon.com/ec2/instance-types/[Learn more about these EC2 instance types^].

link:reference_configs_aws_96.html[Learn more about supported 9.6 configurations in AWS].

=== Supported data disks

One less data disk is now supported for c5, m5, and r5 instances. For single node systems, 22 data disks are supported. For HA pairs, 19 data disks are supported per node.

link:reference_limits_aws_96.html[Learn more about storage limits in AWS].

== Support for DS15_v2 in Azure (12 Feb 2020)

Cloud Volumes ONTAP is now supported with the DS15_v2 virtual machine type in Azure, on both single node systems and HA pairs.

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-memory#dsv2-series-11-15[Learn more about the DSv2 series^].

link:reference_configs_azure_96.html[Learn more about supported 9.6 configurations in Azure].

== 9.6 P5 (26 Dec 2019)

The 9.6 P5 patch release for Cloud Volumes ONTAP is now available through Cloud Manager. Cloud Manager will prompt you to upgrade your existing systems to this patch release. https://mysupport.netapp.com/products/cloud_ontap/9.6P5/index.html[View the list of bugs fixed in the P5 patch^].

== 9.6 P4 (14 Nov 2019)

The 9.6 P4 patch release for Cloud Volumes ONTAP is now available through Cloud Manager. Cloud Manager will prompt you to upgrade your existing systems to this patch release. https://mysupport.netapp.com/products/cloud_ontap/9.6P4/index.html[View the list of bugs fixed in the P4 patch^].

== 9.6 P3 (23 Oct 2019)

The 9.6 P3 patch release for Cloud Volumes ONTAP is now available through Cloud Manager. Cloud Manager will prompt you to upgrade existing systems to this patch release. https://mysupport.netapp.com/products/cloud_ontap/9.6P3/index.html[View the list of bugs fixed in the P3 patch^].

In addition to bug fixes, this release also enables the following:

* Support for the c5.18xlarge instance type in AWS.
* An increase to the maximum aggregate size on single node systems in Azure: 352 TB of raw capacity is now supported.
+
The maximum aggregate size for a single node system was previously 200 TB.

== Pay-as-you-go subscriptions in the GCP Marketplace (6 Oct 2019)

You can now pay for Cloud Volumes ONTAP as you go by subscribing to Cloud Volumes ONTAP in the Google Cloud Platform Marketplace.

https://console.cloud.google.com/marketplace/details/netapp-cloudmanager/cloud-manager?q=NetApp&id=8108721b-10e5-48be-88ed-387031dae492[Google Cloud Platform Marketplace: Cloud Manager for Cloud Volumes ONTAP^]

== General Availability of Cloud Volumes ONTAP in GCP (3 Sept 2019)

Cloud Volumes ONTAP is now generally available in Google Cloud Platform (GCP) when you bring your own license (BYOL). A pay-as-you-go promotion is also available. The promotion offers free licenses for an unlimited number of systems and will expire at the end of September 2019.

* https://docs.netapp.com/us-en/occm/task_getting_started_gcp.html[Learn how to get started in GCP^]
* link:reference_configs_gcp_96.html[View supported configurations]

== 9.6 P2 (29 Aug 2019)

The 9.6 P2 patch release for Cloud Volumes ONTAP is now available through Cloud Manager. Cloud Manager will prompt you to upgrade your existing 9.5 and 9.6 systems to this patch release. https://mysupport.netapp.com/products/cloud_ontap/9.6P2/index.html[View the list of bugs fixed in the P2 patch^].

== 9.6 GA (15 July 2019)

The General Availability (GA) release of Cloud Volumes ONTAP 9.6 is now available. The GA release includes bug fixes. Cloud Manager will prompt you to upgrade your existing systems to this release.

NOTE: Cloud Volumes ONTAP remains in private preview in Google Cloud Platform.

== 9.6 RC1 (16 June 2019)

Cloud Volumes ONTAP 9.6 RC1 is available in AWS, Azure, and now in Google Cloud Platform. This release includes the following features.

* <<Private preview of Cloud Volumes ONTAP in Google Cloud Platform>>
* <<Data tiering with HA pairs in Azure>>
* <<Support for FlexCache volumes>>
* <<Additional ONTAP changes>>

=== Private preview of Cloud Volumes ONTAP in Google Cloud Platform

A private preview of Cloud Volumes ONTAP in Google Cloud Platform is now available. Similar to other cloud providers, Cloud Volumes ONTAP for Google Cloud Platform helps you reduce costs, improve performance, and increase availability.

Cloud Volumes ONTAP is available in GCP as a single node system and supports data tiering to object storage.

To join the private preview, send a request to ng-Cloud-Volume-ONTAP-preview@netapp.com.

=== Data tiering with HA pairs in Azure

Data tiering is now supported with Cloud Volumes ONTAP HA pairs in Microsoft Azure. Data tiering enables automated tiering of inactive data to low-cost Blob storage.

https://docs.netapp.com/us-en/occm/task_tiering.html[Learn how to set up data tiering in Cloud Manager^].

=== Support for FlexCache volumes

A FlexCache volume is a storage volume that caches NFS read data from an origin (or source) volume. Subsequent reads to the cached data result in faster access to that data.

You can use FlexCache volumes to speed up access to data or to offload traffic from heavily accessed volumes. FlexCache volumes help improve performance, especially when clients need to access the same data repeatedly, because the data can be served directly without having to access the origin volume. FlexCache volumes work well for system workloads that are read-intensive.

Cloud Manager does not provide management of FlexCache volumes at this time, but you can use the ONTAP CLI or ONTAP System Manager to create and manage FlexCache volumes:

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-fc-mgmt/home.html[FlexCache Volumes for Faster Data Access Power Guide^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-07F4C213-076D-4FE8-A8E3-410F49498D49.html[Creating FlexCache volumes in System Manager^]

Starting with the 3.7.2 release, Cloud Manager generates a FlexCache license for all new Cloud Volumes ONTAP systems. The license includes a 500 GB usage limit.

=== Additional ONTAP changes

ONTAP 9.6 includes other changes that Cloud Volumes ONTAP users might be interested in:

* SnapMirror replication now supports TLS 1.2 encryption for communication in-flight
* Data tiering (FabricPool) enhancements include:
** Volume move support without needing to re-tier cold data
** SVM disaster recovery support

For more details about the 9.6 release, see the https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508[ONTAP 9 Release Notes^].

== Upgrade notes

* Upgrades of Cloud Volumes ONTAP must be completed from Cloud Manager. You should not upgrade Cloud Volumes ONTAP by using System Manager or the CLI. Doing so can impact system stability.

* You can upgrade to Cloud Volumes ONTAP 9.6 from the 9.5 release.
+
To understand version requirements, refer to http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-dot-upgrade/GUID-AC0EB781-583F-4C90-A4C4-BC7B14CEFD39.html[ONTAP 9 Documentation: Cluster update requirements^].

* The upgrade of a single node system takes the system offline for up to 25 minutes, during which I/O is interrupted.

* Upgrading an HA pair is nondisruptive and I/O is uninterrupted. During this nondisruptive upgrade process, each node is upgraded in tandem to continue serving I/O to clients.
