---
sidebar: sidebar
permalink: reference_new_97.html
keywords: what's new, new, features, release notes, enhancements
summary: Cloud Volumes ONTAP 9.7 includes several new features and enhancements.
---

= What's new in Cloud Volumes ONTAP 9.7
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP 9.7 includes several new features and enhancements.

Additional features and enhancements are also introduced in the latest versions of Cloud Manager. See the https://docs.netapp.com/us-en/occm/reference_new_occm.html[Cloud Manager Release Notes^] for details.

== 9.7 RC1 (15 Dec 2019)

Cloud Volumes ONTAP 9.7 RC1 is available in AWS, Azure, and Google Cloud Platform. This release includes the following:

* <<Flash Cache support in Azure>>
* <<Fix for Azure NIC detach events>>
* <<Additional ONTAP changes>>

=== Flash Cache support in Azure

Cloud Volumes ONTAP now supports the Standard_L8s_v2 VM type with single node, BYOL systems in Azure. This VM type includes local NVMe storage, which Cloud Volumes ONTAP uses as _Flash Cache_.

Flash Cache speeds access to data through real-time intelligent caching of recently read user data and NetApp metadata. It's effective for random read-intensive workloads, including databases, email, and file services.

Deploy new systems using this VM type or modify existing systems to use this VM type and you'll automatically take advantage of Flash Cache.

https://docs.netapp.com/us-en/occm/task_enabling_flash_cache.html[Learn more about enabling Flash Cache on Cloud Volumes ONTAP, including a limitation with data compression^].

=== Fix for Azure NIC detach events

This release addresses an issue with Cloud Volumes ONTAP node reboots from Azure NIC detach events. Cloud Volumes ONTAP will handle these events more gracefully and not disrupt service. Cloud Volumes ONTAP HA pairs will still perform a takeover/give back sequence from Azure freeze maintenance events, but there's no subsequent reboot from a NIC detach that might occur during this time.

=== Additional ONTAP changes

The ONTAP 9.7 release includes other changes that Cloud Volumes ONTAP users might be interested in:

* ???
* ???
* ???

For more details about the 9.7 release, see the https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508[ONTAP 9 Release Notes^].

== Upgrade notes

* You can upgrade to Cloud Volumes ONTAP 9.7 from the 9.3, 9.5, and 9.6 releases. You can perform the upgrade directly from Cloud Manager.
+
To understand version requirements, refer to http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-dot-upgrade/GUID-AC0EB781-583F-4C90-A4C4-BC7B14CEFD39.html[ONTAP 9 Documentation: Cluster update requirements^].

* When you use Cloud Manager to upgrade a single-node system, the upgrade process takes the system offline for up to 25 minutes, during which I/O is interrupted.

* Upgrades of HA pairs are nondisruptive. A nondisruptive upgrade upgrades both nodes in an HA pair concurrently while maintaining service to clients.
