---
sidebar: sidebar
permalink: reference_new_96.html
keywords: what's new, new, features, release notes, enhancements
summary: Cloud Volumes ONTAP 9.6 includes several new features and enhancements.
---

= What's new in Cloud Volumes ONTAP 9.6
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP 9.6 includes several new features and enhancements.

NOTE: Additional features and enhancements are also introduced in the latest versions of Cloud Manager. See the https://docs.netapp.com/us-en/occm/reference_new_occm.html[Cloud Manager Release Notes] for details.

== 9.6 RC1 (11 June 2019)

Cloud Volumes ONTAP 9.6 RC1 is available in AWS, Azure, and now in Google Cloud Platform. This release includes the following features.

=== Private preview of Cloud Volumes ONTAP in Google Cloud Platform

A private preview of Cloud Volumes ONTAP in Google Cloud Platform is now available. Similar to other cloud providers, Cloud Volumes ONTAP for Google Cloud Platform helps you reduce costs, improve performance, and increase availability.

Cloud Volumes ONTAP is available in GCP as a single node system.

To join the private preview, send a request to ng-Cloud-Volume-ONTAP-preview@netapp.com.

=== Data tiering with HA pairs in Azure

Data tiering is now supported with Cloud Volumes ONTAP HA pairs in Microsoft Azure. Data tiering enables automated tiering of inactive data to low-cost Blob object storage.

https://docs.netapp.com/us-en/occm/task_tiering.html[Learn how to set up data tiering in Cloud Manager^].

=== FlexCache

Description here.

== Upgrade notes

* You can upgrade to Cloud Volumes ONTAP 9.6 from the 9.5 release. You can perform the upgrade directly from Cloud Manager.
+
To understand version requirements, refer to http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-dot-upgrade/GUID-AC0EB781-583F-4C90-A4C4-BC7B14CEFD39.html[ONTAP 9 Documentation: Cluster update requirements^].

* When you use Cloud Manager to upgrade a single-node system, the upgrade process takes the system offline for up to 25 minutes, during which I/O is interrupted.

* Upgrades of HA pairs are nondisruptive. A nondisruptive upgrade upgrades both nodes in an HA pair concurrently while maintaining service to clients.
