---
sidebar: sidebar
permalink: reference_storage_limits_94.html
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM
summary: Cloud Volumes ONTAP has storage configuration limits to provide reliable operations. For best performance, do not configure your system at the maximum values.
---

= Storage limits for Cloud Volumes ONTAP 9.4
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP has storage configuration limits to provide reliable operations. For best performance, do not configure your system at the maximum values.

== Capacity limit by license

The capacity limit for a Cloud Volumes ONTAP license includes disk-based storage and object storage used for data tiering.

In Azure, disk limits prevent you from reaching the 368 TB capacity limit by using disks alone. In those cases, you can reach the 368 TB capacity limit by https://docs.netapp.com/us-en/occm/concept_data_tiering.html[tiering inactive data to object storage^]. Refer to <<Capacity and disk limits by Azure VM size,capacity and disk limits by Azure VM size>> for more details.

[cols="30,70",width=60%,options="header"]
|===
| License
| Capacity limit with disks and data tiering

| Explore	| 2 TB (data tiering is not supported with Explore)
| Standard | 10 TB
| Premium | 368 TB
| BYOL | 368 TB

|===

===== For HA, is the license capacity limit per node or for the entire HA pair?

The capacity limit is for the entire HA pair. It is not per node. For example, if you use the Premium license, you can have up to 368 TB of capacity between both nodes.

===== For an HA system in AWS, does mirrored data count against the capacity limit?

No, it doesn't. Data in an AWS HA pair is synchronously mirrored between the nodes so that the data is available in the event of failure. For example, if you purchase an 8 TB disk on node A, Cloud Manager also allocates an 8 TB disk on node B that is used for mirrored data. While 16 TB of capacity was provisioned, only 8 TB counts against the license limit.

== Aggregate and disk limits for Cloud Volumes ONTAP in AWS

In Cloud Volumes ONTAP 9.4, all EC2 instance types can reach the 368 TB capacity limit using EBS storage alone, or by using EBS storage and tiering to S3 (both single node and HA).

[cols=3*,options="header,autowidth"]
|===
| Physical storage
| Parameter
| Limit

.6+| *Aggregates and disks*
| Maximum number of aggregates | 34 for single-node configurations
18 per node in an HA configuration ^1^
| Maximum aggregate size |	96 TB of raw capacity ^2^^,^ ^3^
| Minimum number of disks per aggregate	| 1
| Maximum number of disks per aggregate	| 6
| Maximum disk size | 16 TB
| Maximum number of data disks across all aggregates ^4^ | 34 for single-node configurations
31 per node in an HA configuration
| *RAID groups*	| Maximum per aggregate	| 1
|===

Notes:

. It is not possible to create 18 aggregates on both nodes in an HA pair because doing so would exceed the data disk limit.

. The maximum usable capacity of a 96 TB aggregate is 85.05 TB.

. The aggregate capacity limit is based on the disks that comprise the aggregate. The limit does not include object storage used for data tiering.

. The data disk limit is specific to disks that contain user data. The boot disk and root disk for each node are not included in this limit.

== Aggregate and disk limits for Cloud Volumes ONTAP in Azure

[cols=3*,options="header,autowidth"]
|===
| Physical storage
| Parameter
| Limit

.6+| *Aggregates and disks*
| Maximum number of aggregates | Same as the disk limit
| Maximum aggregate size |	48 TB of raw capacity ^1^^,^ ^2^
| Minimum number of disks per aggregate	| 1
| Maximum number of disks per aggregate	| 12
| Maximum disk size | 4 TB
| Maximum number of data disks across all aggregates ^3^ | Depends on VM size. <<Capacity and disk limits by Azure VM size,See below>>.
| *RAID groups*	| Maximum per aggregate	| 1
|===

Notes:

. The maximum usable capacity of a 48 TB aggregate is 42.52 TB.

. The aggregate capacity limit is based on the disks that comprise the aggregate. The limit does not include object storage used for data tiering.

. The data disk limit is specific to disks that contain user data. The boot disk and root disk for each node are not included in this limit.

=== Capacity and disk limits by Azure VM size

In Azure, single node systems use Standard HDD Managed Disks or Premium SSD Managed Disks, with up to 4 TB per disk. The number of supported disks varies by VM size. The table below shows the maximum capacity by VM size with managed disks alone, and with disks and tiering to object storage.

[cols=4*,options="header,autowidth"]
|===
| VM size
| Max managed disks per node
| Max capacity with managed disks
| Max capacity with managed disks + Blob storage

| DS3_v2 | 15 | 60 TB | Tiering not supported
| DS4_v2 | 31 | 124 TB | 368 TB
| DS5_v2 | 63 | 252 TB | 368 TB
| DS13_v2 | 31 | 124 TB | 368 TB
| DS14_v2 | 63 | 252 TB | 368 TB
|===

== Logical storage limits

[cols=3*,options="header,autowidth"]
|===
| Logical storage
| Parameter
| Limit

| *Storage virtual machines (SVMs)*	| Maximum per node | One data-serving SVM and one or more SVMs used for disaster recovery ^1^
.2+| *Files*	| Maximum size | Volume size dependent
| Maximum per volume |	Volume size dependent, up to 2 billion
| *FlexClone volumes*	| Hierarchical clone depth ^2^ | 499
.3+| *FlexVol volumes*	| Maximum per node |	500
| Minimum size |	20 MB
| Maximum size |	AWS: 76.55 TB of fully provisioned capacity ^3^
Azure: 38.27 TB of fully provisioned capacity ^3^
| *Qtrees* |	Maximum per FlexVol volume |	4,995
| *Snapshot copies* |	Maximum per FlexVol volume |	1,023

|===

Notes:

. Cloud Manager does not provide any setup or orchestration support for SVM disaster recovery. It also does not support storage-related tasks on any additional SVMs. You must use System Manager or the CLI for SVM disaster recovery.

. Hierarchical clone depth is the maximum depth of a nested hierarchy of FlexClone volumes that can be created from a single FlexVol volume.

. The specified limit is based on the assumption that you use Cloud Manager to create a volume and that you keep the aggregate free space ratio at 10 percent, which Cloud Manager sets by default.

== iSCSI storage limits

[cols=3*,options="header,autowidth"]
|===
| iSCSI storage
| Parameter
| Limit

.4+| *LUNs*	| Maximum per node |	1,024
| Maximum number of LUN maps |	1,024
| Maximum size	| 16 TB
| Maximum per volume	| 512
| *igroups*	| Maximum per node | 256
.2+| *Initiators*	| Maximum per node |	512
| Maximum per igroup	| 128
| *iSCSI sessions* |	Maximum per node | 1,024
.2+| *LIFs*	| Maximum per port |	32
| Maximum per portset	| 32
| *Portsets* |	Maximum per node |	256

|===
