---
sidebar: sidebar
permalink: reference_configs_azure_96.html
keywords: vm, explore, standard, premium, byol, capacity, maximum, virtual machine, Cloud Volumes ONTAP, supported, configurations, disks, sizes
summary: Cloud Volumes ONTAP is available in Azure in PAYGO and BYOL configurations. For PAYGO, you can choose from Explore, Standard, or Premium.
---

= Supported configurations for Cloud Volumes ONTAP 9.6 in Azure
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP is available in Azure in two pricing options: pay-as-you-go and Bring Your Own License (BYOL). For pay-as-you-go, you can choose from three configurations: Explore, Standard, or Premium.

== Supported configurations by license

Cloud Volumes ONTAP is available in Azure as a single-node system and as an HA pair.

=== Single node systems

You can choose from the following configurations when deploying Cloud Volumes ONTAP as a single-node system in Azure:

[cols=5*,cols="h,d,d,d,d",options="header"]
|===
|
| Explore
| Standard
| Premium
| BYOL

| Supported virtual machine types | DS3_v2

a|
* DS4_v2
* DS13_v2

a|
* DS5_v2
* DS14_v2
* DS15_v2

a|
* DS3_v2
* DS4_v2
* DS5_v2
* DS13_v2
* DS14_v2
* DS15_v2

| Supported disk types ^1^ 4+| Standard HDD Managed Disks, Standard SSD Managed Disks, and Premium SSD Managed Disks

| Cold data tiering to Blob storage ^2^ | Not supported 3+| Supported

| Maximum system capacity
(disks + object storage) | 2 TB | 10 TB 2+| 368 TB

| Term 3+| Hourly | 12 months

|===

Notes:

. Enhanced write performance is enabled when using SSDs, but not when using the DS3_v2 virtual machine type.

. Data tiering is not supported with the DS3_v2 virtual machine type.

. For Azure region support, see https://cloud.netapp.com/cloud-volumes-global-regions[Cloud Volumes Global Regions^].

=== HA pairs

You can choose from the following configurations when deploying Cloud Volumes ONTAP as an HA pair in Azure:

[cols=5*,cols="h,d,d,d,d",options="header"]
|===
|
| Explore
| Standard
| Premium
| BYOL

| Supported virtual machine types | Not supported

a|
* DS4_v2
* DS13_v2

a|
* DS5_v2
* DS14_v2
* DS15_v2

a|
* DS4_v2
* DS5_v2
* DS13_v2
* DS14_v2
* DS15_v2

| Supported disk types | Not supported 3+| Premium page blobs

| Cold data tiering to Blob storage ^2^ | Not supported 3+| Supported

| Maximum system capacity
(disks + object storage) | Not supported | 10 TB 2+| 368 TB

| Term | Not supported 2+| Hourly | 12 months

|===

Notes:

. For Azure region support, see https://cloud.netapp.com/cloud-volumes-global-regions[Cloud Volumes Global Regions^].

== Supported disk sizes

In Azure, an aggregate can contain up to 12 disks that are all the same type and size.

=== Single node systems

Single node systems use Azure Managed Disks. The following disk sizes are supported:

[cols=3*,options="header"]
|===

| Premium SSD
| Standard SSD
| Standard HDD

a|
* 500 GB
* 1 TB
* 2 TB
* 4 TB
* 8 TB
* 16 TB
* 32 TB

a|
* 100 GB
* 500 GB
* 1 TB
* 2 TB
* 4 TB
* 8 TB
* 16 TB
* 32 TB

a|
* 100 GB
* 500 GB
* 1 TB
* 2 TB
* 4 TB
* 8 TB
* 16 TB
* 32 TB

|===

=== HA pairs

HA pairs use Premium page blobs. The following disk sizes are supported:

* 500 GB
* 1 TB
* 2 TB
* 4 TB
* 8 TB
