---
sidebar: sidebar
permalink: reference_storage_limits_95.html
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, page blobs, ebs, managed disks
summary: Cloud Volumes ONTAP has storage configuration limits to provide reliable operations. For best performance, do not configure your system at the maximum values.
---

= Storage limits for Cloud Volumes ONTAP 9.5
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP has storage configuration limits to provide reliable operations. For best performance, do not configure your system at the maximum values.

== Maximum system capacity by license

The maximum system capacity for a Cloud Volumes ONTAP system is determined by its license. The maximum system capacity includes disk-based storage plus object storage used for data tiering. NetApp doesn't support exceeding this limit.

For some configurations, disk limits prevent you from reaching the 368 TB capacity limit by using disks alone. In those cases, you can reach the 368 TB capacity limit by https://docs.netapp.com/us-en/occm/concept_data_tiering.html[tiering inactive data to object storage^]. Refer to capacity and disk limits below for more details.

[cols="30,70",width=60%,options="header"]
|===
| License
| Maximum system capacity (disks + object storage)

| Explore	| 2 TB (data tiering is not supported with Explore)
| Standard | 10 TB
| Premium | 368 TB
| BYOL | 368 TB

|===

===== For HA, is the license capacity limit per node or for the entire HA pair?

The capacity limit is for the entire HA pair. It is not per node. For example, if you use the Premium license, you can have up to 368 TB of capacity between both nodes.

===== For an HA system in AWS, does mirrored data count against the capacity limit?

No, it doesn't. Data in an AWS HA pair is synchronously mirrored between the nodes so that the data is available in the event of failure. For example, if you purchase an 8 TB disk on node A, Cloud Manager also allocates an 8 TB disk on node B that is used for mirrored data. While 16 TB of capacity was provisioned, only 8 TB counts against the license limit.

== Capacity and disk limits by AWS EC2 instance

Cloud Volumes ONTAP uses EBS volumes as disks. The disk limits below are specific to disks that contain user data. The limits do not include the boot disk and root disk.

=== Single node limits by EC2 instance type

The maximum EBS disk size is 16 TB. The number of supported disks varies by instance type.

The table below shows the maximum capacity by instance type with just EBS disks, and with disks and tiering to object storage.

[cols=4*,options="header,autowidth"]
|===
| Instance type
| Max EBS disks per node
| Max system capacity with EBS
| Max system capacity with EBS + S3

| c4.4xlarge | 34 | 368 TB | 368 TB
| c4.8xlarge | 34 | 368 TB | 368 TB
| c5d.4xlarge | 23 | 368 TB | 368 TB
| c5d.9xlarge | 23 | 368 TB | 368 TB
| m4.xlarge | 34 | 368 TB | 368 TB
| m4.2xlarge | 34 | 368 TB | 368 TB
| m4.4xlarge | 34 | 368 TB | 368 TB
| m5.xlarge | 23 | 368 TB | 368 TB
| m5.2xlarge | 23 | 368 TB | 368 TB
| m5.4xlarge | 23 | 368 TB | 368 TB
| r4.xlarge | 34 | 368 TB | 368 TB
| r4.2xlarge | 34 | 368 TB | 368 TB
| r5.xlarge | 23 | 368 TB | 368 TB
| r5.2xlarge | 23 | 368 TB | 368 TB
| r5d.2xlarge | 23 | 368 TB | 368 TB
|===

=== HA limits by EC2 instance type

The maximum EBS disk size is 16 TB. The number of supported disks varies by instance type.

The table below shows the maximum capacity by instance type with just EBS disks, and with disks and tiering to object storage.

[cols=4*,options="header,autowidth"]
|===
| Instance type
| Max EBS disks per node
| Max system capacity with EBS
| Max system capacity with EBS + S3

| c4.4xlarge | 31 | 368 TB | 368 TB
| c4.8xlarge | 31 | 368 TB | 368 TB
| c5d.4xlarge | 20 | 320 TB | 368 TB
| c5d.9xlarge | 20 | 320 TB | 368 TB
| m4.xlarge | 31 | 368 TB | 368 TB
| m4.2xlarge | 31 | 368 TB | 368 TB
| m4.4xlarge | 31 | 368 TB | 368 TB
| m5.xlarge | 20 | 320 TB | 368 TB
| m5.2xlarge | 20 | 320 TB | 368 TB
| m5.4xlarge | 20 | 320 TB | 368 TB
| r4.xlarge | 31 | 368 TB | 368 TB
| r4.2xlarge | 31 | 368 TB | 368 TB
| r5.xlarge | 20 | 320 TB | 368 TB
| r5.2xlarge | 20 | 320 TB | 368 TB
| r5d.2xlarge | 20 | 320 TB | 368 TB
|===

== Capacity and disk limits by Azure VM size

The disk limits below are specific to disks that contain user data. The limits do not include the boot disk and root disk.

=== Single node limits by VM size

Single node systems can use Standard HDD Managed Disks, Standard SSD Managed Disks, and Premium SSD Managed Disks, with up to 32 TB per disk. The number of supported disks varies by VM size. The table below shows the maximum capacity by VM size with managed disks alone, and with disks and tiering to object storage.

[cols=4*,options="header,autowidth"]
|===
| VM size
| Max managed disks per node
| Max system capacity with managed disks
| Max system capacity with managed disks + Blob storage

| DS3_v2 | 15 | 368 TB | Tiering not supported
| DS4_v2 | 31 | 368 TB | 368 TB
| DS5_v2 | 63 | 368 TB | 368 TB
| DS13_v2 | 31 | 368 TB | 368 TB
| DS14_v2 | 63 | 368 TB | 368 TB
|===

=== HA limits by VM size

HA systems use Premium page blobs as disks, with up to 8 TB per page blob. The number of supported page blobs varies by VM size. The table below shows the maximum capacity by VM size with page blobs only. Data tiering to object storage is not supported with HA systems in Azure.

[cols=4*,options="header,autowidth"]
|===
| VM size
| Max page blobs per node
| Max system capacity with page blobs
| Max system capacity with page blobs + Blob storage

| DS4_v2 | 31 | 368 TB | Tiering not supported
| DS5_v2 | 63 | 368 TB | Tiering not supported
| DS13_v2 | 31 | 368 TB | Tiering not supported
| DS14_v2 | 63 | 368 TB | Tiering not supported
|===

== Aggregate limits in AWS

Cloud Volumes ONTAP uses AWS volumes as disks and groups them into _aggregates_. Aggregates provide storage to volumes.

[cols=2*,options="header,autowidth"]
|===
| Parameter
| Limit

| Maximum number of aggregates |
Single node: Same as the disk limit
HA pairs: 18 in a node ^1^
| Maximum aggregate size | 96 TB of raw capacity ^2^
| Disks per aggregate	| 1-6 ^3^
| Maximum number of RAID groups per aggregate	| 1
|===

Notes:

. It is not possible to create 18 aggregates on both nodes in an HA pair because doing so would exceed the data disk limit.

. The aggregate capacity limit is based on the disks that comprise the aggregate. The limit does not include object storage used for data tiering.

. All disks in an aggregate must be the same size.

== Aggregate limits in Azure

Cloud Volumes ONTAP uses Azure storage as disks and groups them into _aggregates_. Aggregates provide storage to volumes.

[cols=2*,options="header,autowidth"]
|===
| Parameter
| Limit

| Maximum number of aggregates | Same as the disk limit
| Maximum aggregate size |
200 TB of raw capacity for single node ^1^
96 TB of raw capacity for HA pairs ^1^
| Disks per aggregate	| 1-12 ^2^
| Maximum number of RAID groups per aggregate	|
Single node: 1
HA pairs: 6
|===

Notes:

. The aggregate capacity limit is based on the disks that comprise the aggregate. The limit does not include object storage used for data tiering.

. All disks in an aggregate must be the same size.

== Logical storage limits

[cols="22,22,56",width=100%,options="header"]
|===
| Logical storage
| Parameter
| Limit

| *Storage virtual machines (SVMs)*	| Maximum number for Cloud Volumes ONTAP
(HA pair or single node) | One data-serving SVM and one or more SVMs used for disaster recovery. ^1^

The one data-serving SVM spans the entire Cloud Volumes ONTAP system (HA pair or single node).
.2+| *Files*	| Maximum size | Volume size dependent
| Maximum per volume |	Volume size dependent, up to 2 billion
| *FlexClone volumes*	| Hierarchical clone depth ^2^ | 499
.3+| *FlexVol volumes*	| Maximum per node |	500
| Minimum size |	20 MB
| Maximum size | AWS: Dependent on the size of the aggregate ^3^
Azure HA: Dependent on the size of the aggregate ^3^
Azure single node: 100 TB
| *Qtrees* |	Maximum per FlexVol volume |	4,995
| *Snapshot copies* |	Maximum per FlexVol volume |	1,023

|===

Notes:

. Cloud Manager does not provide any setup or orchestration support for SVM disaster recovery. It also does not support storage-related tasks on any additional SVMs. You must use System Manager or the CLI for SVM disaster recovery.

. Hierarchical clone depth is the maximum depth of a nested hierarchy of FlexClone volumes that can be created from a single FlexVol volume.

. Less than 100 TB is supported because aggregates for this configuration are limited to 96 TB of _raw_ capacity.

== iSCSI storage limits

[cols=3*,options="header,autowidth"]
|===
| iSCSI storage
| Parameter
| Limit

.4+| *LUNs*	| Maximum per node |	1,024
| Maximum number of LUN maps |	1,024
| Maximum size	| 16 TB
| Maximum per volume	| 512
| *igroups*	| Maximum per node | 256
.2+| *Initiators*	| Maximum per node |	512
| Maximum per igroup	| 128
| *iSCSI sessions* |	Maximum per node | 1,024
.2+| *LIFs*	| Maximum per port |	32
| Maximum per portset	| 32
| *Portsets* |	Maximum per node |	256

|===
