---
sidebar: sidebar
permalink: reference_limitations_aws_97.html
keywords: limitations, aws, amazon web services, flashe cache, alarms, cloudwatch, giveback, govcloud, c2s
summary: These known limitations are specific to Cloud Volumes ONTAP in Amazon Web Services.
---

= Known limitations for Cloud Volumes ONTAP 9.7 in AWS
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The following known limitations are specific to Cloud Volumes ONTAP in Amazon Web Services. Be sure to also review link:reference_limitations_97.html[Limitations for Cloud Volumes ONTAP 9.7 in all cloud providers].

== HA pairs not supported with AWS Outposts

Single node systems are supported with AWS Outposts but HA pairs aren't supported at this time. 

== Flash Cache limitations

C5D and R5D instance types include local NVMe storage, which Cloud Volumes ONTAP uses as _Flash Cache_. Note the following limitations:

* Compression must be disabled on all volumes to take advantage of the Flash Cache performance improvements.
+
You can choose no storage efficiency when creating a volume from Cloud Manager, or you can create a volume and then http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html[disable data compression by using the CLI^].

* Cache rewarming after a reboot is not supported with Cloud Volumes ONTAP.

== False alarms reported by Amazon CloudWatch

Cloud Volumes ONTAP does not release CPUs when idle, so Amazon CloudWatch can report a high CPU warning for the EC2 instance because it sees 100% usage. You can ignore this alarm. The ONTAP statistics command displays the true usage of the CPUs.

== Cloud Volumes ONTAP HA pairs do not support immediate storage giveback

After a node reboots, the partner must sync data before it can return the storage. The time that it takes to resync data depends on the amount of data written by clients while the node was down and the data write speed during the time of giveback.

== Limitations in the AWS C2S environment

See the https://docs.netapp.com/us-en/occm/media/c2s.pdf[Quick Start Guide for the AWS Commercial Cloud Services Environment^].

== Limitations in AWS GovCloud (US) regions

* Cloud Manager must be deployed in an AWS GovCloud (US) region if you want to launch Cloud Volumes ONTAP instances in any AWS GovCloud (US) region.

* When deployed in an AWS GovCloud (US) region, Cloud Manager cannot discover ONTAP clusters in a NetApp Private Storage for Microsoft Azure configuration or a NetApp Private Storage for SoftLayer configuration.
