---
sidebar: sidebar
permalink: reference_new_991.html
keywords: what's new, new, features, release notes, enhancements
summary: Cloud Volumes ONTAP 9.9.1 includes several new features and enhancements.
---

= What's new in Cloud Volumes ONTAP 9.9.1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP 9.9.1 includes several new features and enhancements.

Additional features and enhancements are also introduced in the latest versions of Cloud Manager. See the https://docs.netapp.com/us-en/occm/reference_new_occm.html[Cloud Manager Release Notes^] for details.

== 9.9.1 Release Candidate (24 May 2021)

The Cloud Volumes ONTAP 9.9.1 Release Candidate is now available in AWS, Azure, and Google Cloud Platform.

In addition to the features introduced with https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508[ONTAP 9.9.1^], this release of Cloud Volumes ONTAP includes the following:

* <<Enhanced performance in AWS with high write speed>>
* <<feature 2>>
* <<feature 3>>

=== Enhanced performance in AWS with high write speed

We have enhanced the throughput performance of Cloud Volumes ONTAP when https://docs.netapp.com/us-en/occm/concept_write_speed.html[high write speed^] is enabled on a supported instance type.

=== io2 system disk in AWS

feature 2 description

=== S3 protocol support in Azure

feature 2 description

== Required version of the Cloud Manager Connector

The Cloud Manager Connector must be running version 3.9.6 or later to deploy new Cloud Volumes ONTAP 9.9.1 systems and to upgrade existing systems to 9.9.1.

== Upgrade notes

* Upgrades of Cloud Volumes ONTAP must be completed from Cloud Manager. You should not upgrade Cloud Volumes ONTAP by using System Manager or the CLI. Doing so can impact system stability.

* You can upgrade to Cloud Volumes ONTAP 9.9.1 from the 9.9.0 release. Cloud Manager will prompt you to upgrade your existing Cloud Volumes ONTAP 9.9.0 systems to the 9.9.1 release.
+
http://docs.netapp.com/us-en/occm/task_updating_ontap_cloud.html#upgrading-cloud-volumes-ontap-from-cloud-manager-notifications[Learn how to upgrade when Cloud Manager notifies you^].

* The upgrade of a single node system takes the system offline for up to 25 minutes, during which I/O is interrupted.

* Upgrading an HA pair is nondisruptive and I/O is uninterrupted. During this nondisruptive upgrade process, each node is upgraded in tandem to continue serving I/O to clients.
